---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    cookie_auth:
      type: apiKey
      in: cookie
paths:
  "/links":
    get:
      summary: list links
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
    post:
      summary: create link
      parameters: []
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                full:
                  type: string
                short:
                  type: string
            examples:
              '0':
                summary: create link
                value:
                  full: http://www.google.com
                  short: 
  "/links/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show link
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
    put:
      summary: update link
      parameters: []
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                full:
                  type: string
                short:
                  type: string
            examples:
              '0':
                summary: update link
                value:
                  full: http://www.google.com
                  short: 
    delete:
      summary: delete link
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
  "/{url}":
    parameters:
    - name: url
      in: path
      description: url
      required: true
      schema:
        type: string
    get:
      summary: list redirects
      responses:
        '200':
          description: successful
  "/session":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              '0':
                summary: create session
                value:
                  email: test@test.com
                  password: password
  "/users":
    get:
      summary: list users
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
    post:
      summary: create user
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                dob:
                  type: string
                gender:
                  type: string
            examples:
              '0':
                summary: create user
                value:
                  email: test@test.com
                  password: password
                  first_name: Test
                  last_name: Testenko
                  dob: 07-05-1993
                  gender: male
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
    put:
      summary: update user
      parameters: []
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                dob:
                  type: string
                gender:
                  type: string
            examples:
              '0':
                summary: update user
                value:
                  email: test@test.com
                  password: password
                  first_name: Test
                  last_name: Testenko
                  dob: 07-05-1993
                  gender: male
    delete:
      summary: delete user
      security:
      - cookie_auth: []
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
